// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWA2uVqHNCk_BGdD6be5tKhM3dWdbqHKE',
    appId: '1:591311386695:web:8dfced97673b82154e1962',
    messagingSenderId: '591311386695',
    projectId: 'vivel-app',
    authDomain: 'vivel-app.firebaseapp.com',
    storageBucket: 'vivel-app.appspot.com',
    measurementId: 'G-T40CN4J9T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV-Ano02tAZ2nMCqHIlc1U-Jp-H9PuC1Y',
    appId: '1:591311386695:android:3508b31fa47b55954e1962',
    messagingSenderId: '591311386695',
    projectId: 'vivel-app',
    storageBucket: 'vivel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsZmJDdbOYyWC-hKG6RfCepDnWhqVcRm4',
    appId: '1:591311386695:ios:af7f8f687403c65c4e1962',
    messagingSenderId: '591311386695',
    projectId: 'vivel-app',
    storageBucket: 'vivel-app.appspot.com',
    iosClientId: '591311386695-6svh5c0c4nf44el4ofcagos20tqlmv6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.vivelapp',
  );
}
